### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by devtooligan** [Mermaid-Chart/issue-tracker#10]
**Is your feature request related to a problem? Please describe.**
Is there a way to change project name?

**Describe the solution you'd like**
I'd like to change the project name.

**Comment by knsv** [comment]
Hi!

That is a reasonable thing to want to do, and fortunately, you can. In the project list, click on the little cog.

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/65e23f87-24a4-4b25-b8d9-dbc90851a41a)

Then in the side panel to the right, you can click on the project title and edit it.

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/501533c6-d8d8-43c5-a662-540dab0ff08d)

I hope that helps.

**Comment by devtooligan** [comment]
That's what I thought but it does not allow me to overwrite it, the entire area is greyed out.  i am using Chrome and on the "PRo" plan 

<img width="1247" alt="Screenshot 2023-08-22 at 10 31 54 PM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/71567643/4fbb9f23-770d-45d9-bb54-197d6bce6965">

**Comment by knsv** [comment]
Aha, it's the personal project. Understand. If you create more projects you can name them to whatever you want, but the personal project is special and locked to the name personal.

 Thanks for bringing this up. But this is unnecessarily restrictive and should be fixed. I will add a ticket to our backlog for this.

**Comment by devtooligan** [comment]
fwiw i created a new project and also cannot change the name of that project

<img width="1256" alt="Screenshot 2023-09-11 at 1 54 02 PM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/71567643/537422fd-dd8b-41f5-bef3-913dcc2e5737">

**Comment by jgreywolf** [comment]
@devtooligan first of all let me apologize for the delay in response.

To your issue, if you click on the text "frax", it should become a text input where you can change the name.

I realize this is not obvious, and I will add an item to backlog to add visual cues

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/300077/02568038-039c-4e3d-a6fe-7bb7c61f93b0)

**Comment by nirname** [comment]
I agree with @devtooligan on that.

My personal project is called "personal". By some obscure reason I'd like to have it renamed, for instance I'd like to start titles with capital letters, aka "Personal".

But I do not have an opportunity to do so.

**Describe the solution you'd like**

An interface edit button, or "pencil" icon somewhere near the title of my personal project.

**Comment by jgreywolf** [comment]
This has been resolved as of late January/early February
