### ISSUE TITLE
User state persistence

### ISSUE THREAD

**Issue by Ephron-WL** [Mermaid-Chart/issue-tracker#11]
Zoom/Pan state is being lost when the user 

1. edits the diagram definition and mermaid is resynced (autosynced)
2. refreshes the browser
3. the user has the zoom/pan switch in the "on" state

**Comment by knsv** [comment]
OK, that is a good point. We should fix that!

**Comment by knsv** [comment]
A fix from @syed1dev has just been released. Happy diagramming.
