### ISSUE TITLE
Can't upgrade account to premium once Free tier expired.

### ISSUE THREAD

**Issue by a-wyatt** [Mermaid-Chart/issue-tracker#12]
**Describe the bug**
My free tier expired. In trying to upgrade I click on the Google sign option and before I get a chance to upgrade the screen jumps to 402 Free tier expired. I can't then upgrade with that email address to use the product.

**To Reproduce**
1. Go to https://www.mermaidchart.com/app/login
2. Click on "Continue with Google

**Expected behavior**
Don't assume I want to start editing provide home page to enable an upgrade 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 115.0.5790.170

**Comment by jgreywolf** [comment]
@a-wyatt I am sorry that you have run into this error, and not able to access the site. 
I have logged this issue internally, and we will be getting this resolved in our next sprint.  I will update you here on progress

**Comment by pbrolin47** [comment]
An upgrade to Pro button has been added to the 402-page
