### ISSUE TITLE
Delete Diagram - No Button to Accept

### ISSUE THREAD

**Issue by lfbarbieri-ipl** [Mermaid-Chart/issue-tracker#13]
**Describe the bug**
When I go to delete a diagram, a popup appears.  It shows a "Cancel" button, but there is no "Ok" button or some way to accept the deletion.

**To Reproduce**
1. Go to Projects and select a project
2. Click on a diagram and click gear(settings) button
3. Click ellipse ('...'), select Delete diagram 
4. Pop up appears, with no button to confirm the deletion

**Expected behavior**
To have an ok or simliar button to be able to confirm deletion

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge
 - Version: Version 116.0.1938.54 (Official build) (64-bit)

![Deletion Confirmation](https://github.com/Mermaid-Chart/issue-tracker/assets/55300966/a86f371e-e36f-4d89-9c97-64d620474984)

**Comment by knsv** [comment]
Thanks for reporting! We will fix this as soon as possible.

The button is there but colored in a unfortunate way...

**Comment by lfbarbieri-ipl** [comment]
Thanks knsv, I eventually did manage to find it.  Didn't see it earlier, but I can see the white text in screenshot I provided.

**Comment by huynhicode** [comment]
Thanks, @knsv!

Hi @lfbarbieri-ipl, thanks for bringing this to our attention.

I have submitted a fix for this issue.

<img width="680" alt="Screenshot 2023-08-24 at 11 18 43 PM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/35910788/109c2a9e-77d6-45a8-83df-cd67274d2f93">
