### ISSUE TITLE
Error PNG download

### ISSUE THREAD

**Issue by rafaelccorrea** [Mermaid-Chart/issue-tracker#14]
Hello everybody...
I came across a problem when I went to upload the diagram to PNG...
I came across the message.

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/68115778/5bc65f33-54cb-48b1-a589-bb671b52a424)

diagram used.

flowchart TD
  subgraph Confirmação de email
    usuário(usuário) ---> verifica("No painel administrativo de usuários, é possível verificar se cada usuário confirmou o e-mail.") --> |Parâmetros de busca: 
    q: Pesquise usuários por nome, e-mail e tipo
    type: Pesquise usuários por tipo
    email: Pesquise usuários por email
    name: Pesquise usuários por nome 
    |routa_verifica_emails_confirm(ROTA_GET: auth/email-confirmations) -->
    usuário_decisão{Usuário tem email confirmado?}
    usuário_decisão -->|Sim| fim_execução(Sem Execução)
    usuário_decisão -->|Não| envia_email(Faz o envio de um email para confirmação.) -->
    rota_envio_email(ROTA_POST: /auth/email-confirmations/sends) -->
    servidor[Servidor]
    servidor -->|Resposta: status: 200|decisão{Recebeu email de confirmação?}
    decisão -->|Sim| confirm("Confirmação de email do usuário.") ---> 
    |"Dados enviados ex: {
        email: string,
        newPassword: string,
        code: uuid,
        userId: string }"
    |rota_confirm_email("ROTA_POST: auth/email-confirmations") -->
    request[Servidor]
    request -->|Resposta: status: 200| result[Fim da execução]
    decisão -->|Não| envia_email
  end

I also tried to upload the svg but the diagram data is empty!

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/68115778/cbfc5642-49f7-4d6f-95d4-62d28584fd88)

This problem in my view is also affecting when making the link available to the public since the page gives a 404...

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/68115778/6618b29c-7ec6-4eb1-8ff1-b093778e3933)

**Comment by jgreywolf** [comment]
@rafaelccorrea Thank you for reporting this, we just started noticing this today as well, and we are investigating to find the issue

**Comment by pbrolin47** [comment]
@rafaelccorrea We have identified and rectified an issue that is related to the difficulty you encountered. Can you please try to export the diagram as PNG and SVG and see if the problems are still present?
Regards, Per

**Comment by rafaelccorrea** [comment]
Sorry for the delay, I just tested it and it worked...
