### ISSUE TITLE
Internal Error when attempting to use the MermaidChart ChatGPT plugin

### ISSUE THREAD

**Issue by natea** [Mermaid-Chart/issue-tracker#15]
**Describe the bug**
I tried to use the MermaidChart plugin for ChatGPT, but after giving it the text for the diagram, it returned an internal server.

**To Reproduce**
1. Upgrade to ChatGPT Plus
2. Install the MermaidChart plugin from the plugin store
3. Provide some text for a Mermaid diagram
4. Tell it to use the MermaidChart plugin

**Expected behavior**
I expected that it would return a visualization of the diagram, but instead it returned an error.

**Screenshots**
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/118984/ff533f71-6097-4d55-acb1-4b96e2a61255)

**Desktop (please complete the following information):**
 - OS: MacOSX Ventura
 - Browse: Arc (Chromium)
 - Version: 1.5.0

**Additional context**

Here is the Mermaid text I provided:

```
graph TD
A[Customer calls Clerk] --> B[Clerk starts a new Order]
B --> C{Order type?}
C --> D[Delivery]
C --> E[Pickup]
D --> F{Distance?}
F --> G[< 5 miles]
G --> H[$1 delivery charge]
F --> I[5 - 10 miles]
I --> J[$5 delivery charge]
F --> K[> 10 miles]
D --> L{Today is Tuesday?}
L --> M{Mention "PizzaTuesdays"?}
M --> N[10% discount]
```

**Comment by knsv** [comment]
Thanks for reaching out!

ChatGPT has problems with quotes it seems...
The quotes around "PizzaTuesdays" are the issue.

We have an integrated chatbot using ChatGPT in the Mermaid Chart service. There, you can chat about the diagram with CHatGPT and also directly edit the code, sometimes, that can be quicker. 

There is also a repair button that uses ChatGPT together with the error message from Mermaid to try to fix syntax problems.

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/7a5dc49f-f541-446a-b113-4a8f8efc2803)

Apart from that we will look at the plugin and see if we improve the instructions for ChatGPT.

I hope that helps.

**Comment by jgreywolf** [comment]
Closing this issue based on comments above. We are continuing to improve interactions between Mermaid Chart and ChatGPT which will also assist with issues like this
