### ISSUE TITLE
Comments break diagrams

### ISSUE THREAD

**Issue by DavidCampbell-architect** [Mermaid-Chart/issue-tracker#18]
**Describe the bug**
All of my existing diagrams no longer generate due to a syntax error. This error is incorrect and seems to be caused by the editor not understanding %% lines. If I fool around with the %% lines, I can get the diagram to generate again, even restoring the markdown to exactly what it was before.

**To Reproduce**
I'll keep one of my diagrams in the error state. It is set to public. Take a look at it.
https://www.mermaidchart.com/raw/bc5e4ccd-bb4a-4286-abef-4e01aaed3acd?version=v0.1&theme=light&format=svg

**Expected behavior**
Diagram is generated without issue.

**Screenshots**
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/138038670/3a199758-d1f9-4694-915c-50946666ce21)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave version
 - Version: 1.58.127

**Additional context**
The diagrams generate fine on mermaid.live

**Comment by jgreywolf** [comment]
@DavidCampbell-architect - are you still having an issue with this?  The diagram you said you would keep in error state is rendering fine on my end.

If this is still an issue, can you post the code above, to make it easier to work on reproducing the issue?

**Comment by DavidCampbell-architect** [comment]
I still get the same error. Code is below.
```
%% Key for context diagrams
graph LR

%% formatting
classDef outerNodes stroke:#70a3bd,stroke-width:4px
classDef keyNode stroke-width:4px
classDef highlightedNode fill:#f4cccc,stroke:#e30613,stroke-width:2px
classDef noteNode fill:#FFFF00

subgraph Key
    subgraph outer[Outer Process]
        subgraph inner[Inner Process]
        end
    end
    outer:::outerNodes
    outer -->|"logic flow"| Process
    reportToBeWorked[externalized report]:::highlightedNode
    notes>"Note"]:::noteNode

    reportToBeWorked ~~~ notes
end
Key:::keyNode
```

**Comment by jgreywolf** [comment]
@DavidCampbell-architect  I see what you are saying.  I notice that if I add a line break between the comment and the next line it work.  Except for the first line.  

I noticed that the same error is happening in the mermaidJs live editor, which makes me think that the error is happening within mermaidJs itself.

I am continuing to investigate - since we do have tests specific to this scenario that are passing, and I need to dig down to determine why

**Comment by jgreywolf** [comment]
FYI - I have not forgotten this.  I am still working on tracking the source
of this down, and will update early next week

*Justin Greywolf*
*Software Engineer* - Mermaid Chart
https://www.mermaidchart.com

**Comment by jgreywolf** [comment]
@DavidCampbell-architect It looks like this is now working in mermaidchart.com editor:

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/300077/74bcb76c-9af9-499a-b9f2-1894019952b7)

**Comment by DavidCampbell-architect** [comment]
Yes, it looks like it is working now. Thanks.
