### ISSUE TITLE
Can not correctly display chinese comments

### ISSUE THREAD

**Issue by Dingwenxue** [Mermaid-Chart/issue-tracker#2]
1. preview can correctly displaying chinese comments on flow chart.
https://www.mermaidchart.com/app/projects/personal/documents/ca1a97cb-5fd8-483f-9a22-2137ffa5fe36/version/v0.1/edit
3. if  you using  high-resolution button to generate png file, and open png file you will find it can not correctly display chinese comments on flow chart.

**Comment by knsv** [comment]
Thanks for reporting this @Dingwenxue!

We will look at this.

**Comment by knsv** [comment]
@Dingwenxue I believe this is fixed now! Don't hesitate to reopen the issue if you can reproduce the issue.
