### ISSUE TITLE
Manual Editing Capability for Diagrams

### ISSUE THREAD

**Issue by oryx-it** [Mermaid-Chart/issue-tracker#22]
**Background**
We frequently use ChatGPT to generate diagrams. While it's an invaluable tool, I find that the subsequent fine-tuning, which is solely dependent on code modifications, can be time-consuming. Moreover, the website responsiveness isn't always optimal, further prolonging the process.

**Request**
Introduce a functionality that allows users to manually edit the diagrams—specifically, elements like arrows, text, and shapes—directly through a user-friendly graphical interface.

Maintain the existing option to control diagrams through code for those who prefer this method, but complement it with the manual editing tool.

**Rationale**
Manual editing can provide users with the flexibility to make quick adjustments without the need to delve back into the code, especially for minor fixes. This will streamline the diagram creation and adjustment process, making it more efficient and user-friendly. The combination of manual and code-based controls could cater to a broader range of user preferences and needs.

**Comment by pbrolin47** [comment]
Thank you for suggestion to improve Mermaid Chart. We will take the suggestion into consideration when planning future releases

**Comment by oryx-it** [comment]
I truly appreciate the potential of this tool, but currently, its user interface feels less intuitive, especially when dealing with large-scale diagrams.

Speaking from my perspective as an entrepreneur, product developer, and someone who genuinely wishes for the tool's success, I believe that a few important changes would bring this to a new level.

While I may not have the bandwidth to create individual GitHub tickets for every suggestion, which might not always be interpreted as intended, I'd be more than willing to provide direct feedback via a call. If you're interested please let me know.

**Comment by jgreywolf** [comment]
I am going to close this as we are tracking internally - however, we are in the process of implementing a limited "visual" editing functionality from the diagram viewer as you suggested, beginning with the ability to add and link nodes and edit edges/arrows.
We plan to have the initial release before end of CY 2023, and will continue to release incremental enhancements
