### ISSUE TITLE
Export as PNG hangs

### ISSUE THREAD

**Issue by DavidCampbell-architect** [Mermaid-Chart/issue-tracker#24]
**Describe the bug**
When I try to use the "Export as PNG" option, the document hangs indefinitely with the "Generating hi-res PNG" animation playing.

**To Reproduce**

1. Open a diagram
2. Click the Export icon in the sidebar menu on the left
3. Click the "Export as PNG" option in the menu that pops up

**Expected behavior**
An explorer window pops up so I can save the diagram as a PNG file.

**Screenshots**
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/138038670/0ee1f66d-3377-49c3-9df6-a1bee2c8d474)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave 
 - Version: Version 1.58.135 Chromium: 117.0.5938.140
 - Also happens on: Edge Version 117.0.2045.47 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nirname** [comment]
The same on desktop, Ubuntu, Chrome. It hangs and I am not able to hide the overlay or escape the process.
![image (15)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/77271e67-3dbf-44a7-a475-6bf7d0293d44)

**Comment by pbrolin47** [comment]
Thanks for the feedback. We will look into this

**Comment by DavidCampbell-architect** [comment]
This appears to be working now.

**Comment by aloisklink** [comment]
It looks like there was a bug that was causing the "Export as PNG" process to freeze if there was ever an error.

Now, trying to render an invalid diagram (or any other rendering error) will throw an error almost instantly instead of hanging.
