### ISSUE TITLE
Dark theme is hard to read

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#25]
**Describe the bug**

May be this is not a bug, but blue color on the dark background is always hard to distinguish

**Screenshots**

![image (9)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/ddfc732d-56a9-4223-ac7e-793e07cd9bb5)

**Comment by pbrolin47** [comment]
Thank you for the feedback. We are working on a solution with a different color scheme when dark theme is enabled to make the diagrams more easily read

**Comment by knsv** [comment]
This issue has been addressed with improvements even though this work is continuous. Please reopen if you are still having issues.
