### ISSUE TITLE
Sample diagrams does not fit my laptop screen, 2 scroll bars

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#26]
**Describe the bug**

I am using a laptop, rather small and light one. Sample diagrams popup is not adaptive and does not fit. 2 scroll bars are visible, and even if it scroll both to the very beginning I do not see some content

**To Reproduce**

Take a chance with Chrome developing tools to see how it would look with different screen dimensions

**Expected behavior**

Pop up fits, all the content is visible

**Screenshots**

![image (10)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/0f09478e-4e03-4740-8125-ffeb80155f63)

**Comment by pbrolin47** [comment]
Thanks for the feedback. We will take the issue into consideration when planning future releases

**Comment by jgreywolf** [comment]
@nirname Can you please check this again and see if this is resolved. Samples has been moved out of a dialog box, and into side panel similar to other items in editor

**Comment by nirname** [comment]
Yep, menu is a sidebar now, looks more or less ok, thanks
