### ISSUE TITLE
Switching between diagrams and presentations ruins breadcrumbs

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#27]
**Describe the bug**

For a split second while switching between "diagrams" and "presentations" tabs some internal hash-code is visible in the middle of the breadcrumbs.

**To Reproduce**

1. Go to personal project
2. Click on another tab  "diagrams" and "presentations"
3. See what is happening with the breadcrumbs

**Expected behavior**

Breadcrumbs should be always pretty

**Screenshots**

![image (12)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/6053d2a1-fa56-4963-a621-591f3ed32d31)

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the issue into consideration when planning future releases.

**Comment by jgreywolf** [comment]
@nirname I am going to close this item, as we are tracking internally.
We have a suite of improvements planned for presentations that we will be rolling out incrementally over the 1-2 months

**Comment by nirname** [comment]
Ok. The glitch is still present, waiting for updates.
