### ISSUE TITLE
Untitled diagrams are not searchable

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#28]
**Describe the bug**

I have some untitled diagrams. They are not searchable. When typing "untitled" in the search string nothing happens.

**To Reproduce**

1. Create a couple of diagrams without specific title (this is default behavior), or erase the title
2. Go to diagrams list and start typing "untitled"

Diagrams disappear, no matter what case

**Expected behavior**

To my mind there are several options:

- Either untitled diagrams should stay regardless of the search string
- They should be searchable by "untitled" text
- We need some special tags (:no-title)

**Screenshots**

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/652bf67e-f24d-47f8-858f-2c7735522b82)

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/4d3a20be-5290-4d83-87ae-67b279e847e8)

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the suggestion into consideration when planning future releases.

**Comment by jgreywolf** [comment]
This has been addressed. And you can now search by untitled.

**Comment by nirname** [comment]
Confirm
