### ISSUE TITLE
Text is not formatted properly in the "out of sync" notification

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#29]
**Describe the bug**

Square bracket is separated from the text, which is not good for the normal text (not a code)

**To Reproduce**

1. Turn off auto-sync in settings
2. Update your code

**Expected behavior**

No "hanging" square brackets

**Screenshots**

![image (17)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/12c8c880-8c59-4f56-8035-914ba33b85fc)

**Desktop:**

 - OS: Ubuntu
 - Browser Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the issue into consideration when planning future releases.

**Comment by jgreywolf** [comment]
@nirname This issue should be resolved. Please verify on your end to confirm
