### ISSUE TITLE
Allow for users to reorganize their files

### ISSUE THREAD

**Issue by bacchist** [Mermaid-Chart/issue-tracker#3]
**Is your feature request related to a problem? Please describe.**
I am using your ChatGPT plugin to generate diagrams. Following the link provided places the diagram under the "personal" project category, with no clear way to move it.

**Describe the solution you'd like**
I'd like to be able to relocate diagram files to other projects. Ideally there would be a way to do this for multiple diagrams in one action.

**Describe alternatives you've considered**
Copying and pasting into a new diagram in the right place and then deleting the original, but that's not a very user-friendly process.

**Additional context**
Organizing diagrams is a bit cumbersome in general. It was not clear how to create a personal project, so I created a team and then a team project. All I wanted to do was the equivalent of creating a new folder and putting the relevant files in it.

**Comment by DavidCampbell-architect** [comment]
This is the very first thing I tried to do when I subscribed to Pro. I wanted to move my existing diagrams I made in the personal project to a team project. I was surprised that file reorganization wasn't possible.

**Comment by knsv** [comment]
Thanks for adding the issue and the feedback. This function is actively being worked on and will be released shortly.

In the first release it will be possible to move a diagram using a menu option in the preview panel for a diagram:
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/18e75089-7a65-460c-9e84-68e736a227e9)

We are also considering making it possible to move several diagrams in one go in a second iteration of the function.

**Comment by knsv** [comment]
This feature is released now. I hope you like it!
