### ISSUE TITLE
Diagrams from the history or examples are not loaded correctly

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#30]
**Describe the bug**

I loaded wrong diagram, one with a mistake in it from the history.
Immediately after I loaded a correct one from the history, and I still see the error, as if it is wrong.

So there is nothing wrong with the second one, I simply needed to tap enter somewhere in the code, but it was not rendered right after restoring

**To Reproduce**

1. Create a decent history to choose from
2. Select wrong version from history
3. Immediately select correct version from history

Correct diagram is not rendered

**Expected behavior**

Correct diagram must be rendered right after user presses "restore" button

**Screenshots**

<img width=250 src="https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/98ff0d3a-e9eb-42e3-93bc-85e60a839c13"/>
<img width=250 src="https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/715ac988-3f97-448c-9ba9-d708ac37bfdd"/>
<img width=250  src="https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/650dfa2b-9049-44a2-a2eb-186faf6473fd"/>

**Desktop**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by nirname** [comment]
Diagrams from the examples behave in the similar way. If there was an error before the diagram loaded from the examples will not be rendered immediately

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the issue into consideration when planning future releases

**Comment by jgreywolf** [comment]
@nirname Can you check and see if this is resolved for you? We have a few bug fixes recently in this area that should have made an impact

**Comment by nirname** [comment]
Cannot reproduce it anymore
