### ISSUE TITLE
Wrong hints for code snippets

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#31]
**Describe the bug**

Wrong diagram title git-graph (there is no `git-graph` only `gitGraph`) is mistakenly taken as `graph` by "shapes helper". Sidebar thinks it is `graph`, although it is not

**To Reproduce**

1. Type literally anything that ends with `graph` at the very beginning, `sankey_graph`, `git-graph`
2. Open sidebar
3. You will get `flowchart` helpers

**Expected behavior**

Either empty or a full list (for all sorts of diagrams) inside snippets

**Screenshots**

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/b2302a75-d694-44e0-80ca-e40260485f20)

**Desktop:**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by nirname** [comment]
Information at the left button behaves the same way

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the issue into consideration when planning future releases

**Comment by jgreywolf** [comment]
This issue has been resolved
