### ISSUE TITLE
Rename saved versions or save diagram manually

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#32]
**Is your feature request related to a problem? Please describe.**

Previously saved versions are not descriptive.

When I load the previously saved version I'd like to have some information that would explicitly showed that.
Right now it simply adds one more line to the history of changes.
It is impossible to say which one was created while editing, and which one was created when I pressed restore button.

**Describe the solution you'd like**

I think that renaming, or simply naming saved versions would do the trick. When auto save is being triggered it would be great that this would also contain a name or would reference it's ancestor.

At the left is what is now. At the right is what I'd love to see.

<img height=300 src="https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/e8939e26-8019-4cf5-9dbf-20f581e4bbd4" />
<img height=300  src="https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/09250833-32fb-4757-8447-8e3e99ccc989" />

**Describe alternatives you've considered**

A tree of changes. Many different tools do this, but it can be a bit excessive.

**Comment by pbrolin47** [comment]
Thank you for the suggestion. We will take it into consideration when planning future releases

**Comment by jgreywolf** [comment]
@nirname I have changed the way that timeline is displayed and handles entries. One of the things I added was the ability to change the name to something that makes more sense. This will be released within the next couple of days

**Comment by nirname** [comment]
@jgreywolf Thank you, I will try it as soon as it is released

**Comment by jgreywolf** [comment]
This has been released to prod
