### ISSUE TITLE
Uploading images for a project does not work

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#34]
**Describe the bug**

Project editing menu says nothing about cover-images limitations (extensions, size, etc). I press upload button, and nothing happens.

**To Reproduce**

1. Open project details
2. Click on 'upload image'
3. Select image from the window
4. Nothing happens

**Expected behavior**

When I upload an image I expect it to be displayed as a project cover, right in the project details menu and on the respective thumbnail as well.

**Screenshots**

[Screencast from 04.10.2023 22:05:53.webm](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/ebbea51b-aed4-4bfb-a2cf-9ab2a0ec4668)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by jgreywolf** [comment]
@nirname This functionality was disabled last week due to a bug that was discovered.  This was resolved fairly quickly, and you should see this working correctly now.

**Comment by nirname** [comment]
@jgreywolf Nope, the same problem. I am uploading image for the personal project, I don't have premium subscription. Can it make the difference?

**Comment by jgreywolf** [comment]
You are right - sorry, I see that the issue logged on our side has not been completed yet, I thought it had been

**Comment by jgreywolf** [comment]
The fix for this has been pushed to production

**Comment by nirname** [comment]
@jgreywolf confirmed
