### ISSUE TITLE
Diagrams selection for presentation breaks page and works slow

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#35]
**Describe the bug**

There are 2 parts:

When switching between "all the diagrams selected" and "some of the selected" while editing presentation you can clearly see how some indentation or html changes, so the page content moves unexpectedly.

Breadcrumbs are also ruined.

The second part is rather from the engineering perspective. Every time I select or deselect a diagram it takes really long time. The page makes requests for each and every diagram every time even though I only selected or deselected one of them. This can be seen in development tools, network tab, Chrome. Right now page freezes for some time, does not matter how may diagrams are there.

**To Reproduce**

1. Go to presentation editing
2. Select all diagrams
3. Deselect some of them

**Expected behavior**

Page's content does not move.
Diagram select or deselect works fast, without delay. 
Even if there is a problem with the internet, it's better to display with some spinner or progress bar on top of the diagram that is being selected / or deselected. 

**Screenshots**

[Screencast from 04.10.2023 22:10:08.webm](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/4e68482a-4b5f-458c-9d19-1fe845185de4)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by pbrolin47** [comment]
Thank you for the feedback. We will take the issue into consideration for future releases

**Comment by jgreywolf** [comment]
@nirname I am going to close this item, as we are tracking internally.
We have a suite of improvements planned for presentations that we will be rolling out incrementally over the 1-2 months
