### ISSUE TITLE
Presentations reorder themselves unexpectedly

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#36]
**Describe the bug**

Presentations reorder themselves which undesirably interrupts editing

**To Reproduce**

1. Create a bunch of presentations
2. Start renaming them

After renaming the list of presentation is reordered and if you happen to rename another presentation at that point it stops you and interferes with your job.

**Expected behavior**

Presentations stays at their places and they are reordered only when a user reloads the page or asks them to be reordered. At least the presentation which title is being edited right now should stay in place

**Screenshots**

[Screencast from 04.10.2023 22:37:37.webm](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/db9ecb66-5e0a-4d1e-8581-dda98b5dab17)

**Desktop (please complete the following information):**

 - OS: Ubuntu
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by knsv** [comment]
Thanks, we should fix that.

**Comment by jgreywolf** [comment]
@nirname I am going to close this item, as we are tracking internally.
We have a suite of improvements planned for presentations that we will be rolling out incrementally over the 1-2 months
