### ISSUE TITLE
Cannot create image of  flowchart

### ISSUE THREAD

**Issue by tommytikea** [Mermaid-Chart/issue-tracker#38]
**Describe the bug**
Trying to create an image of a flowchart

**To Reproduce**
1. create a flowchart
2. Click on Export diagram
Nothing happens 

**Expected behavior**
See some option to export to an image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser Safari
 - Version [Latest

**Additional context**

**Comment by knsv** [comment]
Hi, first of all, thanks for reporting. The functionality moved when we refreshed the editor layout. There is a new icon at the bottom of the toolbar to the left where you can find the functionality, see the attached screenshot.

<img width="214" alt="image" src="https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/496c39aa-e3b5-472d-a612-3757b05040be">

**Comment by tommytikea** [comment]
Hi again,

Yes this is the button i reported, the popup is not showing up. Nothing happends when i click this icon.

Tommy
________________________________

**Comment by huynhicode** [comment]
@tommytikea It appears that the export dropdown is not functional in Safari. 

We have logged this bug and will update this ticket when there is a resolution.

Thanks again for logging this issue!

**Comment by jgreywolf** [comment]
Closing this item in favor of #39 which i specific to safari browser
