### ISSUE TITLE
Expand CSS Style Combinations (Themes)

### ISSUE THREAD

**Issue by Ephron-WL** [Mermaid-Chart/issue-tracker#4]
I prefer the CSS styles for mind map in use on mermaid.live, as they are more vibrant.  I suppose I'd suggest a greater set of possible themes beyond the two currently in use.  The mind map is a bit challenging to read easily because the color contrast between the drab background colors and the foreground text are not great enough.  Otherwise, great work!

**Comment by knsv** [comment]
Thanks for your feedback and we hear you! 

We are adding this into the backlog.

**Comment by knsv** [comment]
We have released a theme selector to the editor whith a drop down for selecting the theme to be used for the mermaid diagrams
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/5837277/428c9daf-3f7d-4f66-abdb-efde267b3e6f)

I hope you will like this new feature!
