### ISSUE TITLE
hCaptcha does not show on Firefox/Linux

### ISSUE THREAD

**Issue by ilrico** [Mermaid-Chart/issue-tracker#40]
**Describe the bug**
hCaptcha does not show on login or new user, on Firefox 118.0.2 and linux (Debian)
The button keeps spinning for ages. Reproduced bug a dozen of times before giving up.
No problem with Firefox running under Windows 11.

**To Reproduce**
Under specified config, go to login page and input credentials, then click on hCaptcha button

**Expected behavior**
Should show an image with instructions

**Desktop (please complete the following information):**
 - OS: GNU/Linux Debian
 - Browser Firefox
 - Version 118.0.2 (also tested on 113, same issue)

**Comment by huynhicode** [comment]
@ilrico Thanks for logging this issue.  We will take a look and update this issue when there is a resolution.

**Comment by jgreywolf** [comment]
Can you try this again?  We have made extensive updates to the hCapthca system

**Comment by sidharthv96** [comment]
We have switched to Turnstile, and tested in all major browsers.
