### ISSUE TITLE
Hello is it me your locking  for to up grade your vision to something  I haven't  already done in this beautiful journey we all have had bombing heads with my creation in paint!

### ISSUE THREAD

**Issue by Western92** [Mermaid-Chart/issue-tracker#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by huynhicode** [comment]
@Western92 Thanks for reaching out! 

I am sorry, I am not able to understand your message. Would you please clarify what the issue is?

Thank you!

**Comment by knsv** [comment]
Closing this one for now
