### ISSUE TITLE
Impossible to edit or create a diagram 

### ISSUE THREAD

**Issue by Alicetost** [Mermaid-Chart/issue-tracker#43]
**Describe the bug**
it is impossibel to create or edit an existing diagram I have an error each time > see screnshot 

**To Reproduce**
1. Go to my project
2. Click on edit diagram 

**Expected behavior**
I expect to have the editor opened 

**Screenshots**
<img width="1389" alt="Capture d’écran 2023-11-03 à 09 51 02" src="https://github.com/Mermaid-Chart/issue-tracker/assets/97668467/6b5458be-a236-48f1-9b06-14ccccdf8f9c">
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pbrolin47** [comment]
Hello,
Sorry for the problems you experience.
1) If you logout and login again, are the problems still present??

**Comment by knsv** [comment]
Closing this one for now, please reopen if the problem persists
