### ISSUE TITLE
replacing diagrams does not allow undo

### ISSUE THREAD

**Issue by devtooligan** [Mermaid-Chart/issue-tracker#45]
**Is your feature request related to a problem? Please describe.**
I just lost a diagram I had spent a fair amount of time on.  I had forgotten how to do loops so I clicked on the Sample Diagrams and selected the example with loops.  The UI does warn "This will replace your current diagram code." but I figured I could still undo after.  

**Describe the solution you'd like**
Would be nice if undo worked after replacing the diagram

**Describe alternatives you've considered**
or at minimum a stronger warning that the action it cannot be undone. 

also, with all the auto-syncing / auto-saving, would be nice to be able to revert to a previous version.

**Comment by huynhicode** [comment]
@devtooligan Thanks for the invaluable feedback and apologies for the frustrating experience!

There is a Timeline menu option that allows you to restore previous versions of your diagram.  It's the 5th icon down from the top and looks like a clock.

Are you able to restore your previous diagram?

<img width="569" alt="Screenshot 2023-11-19 at 5 57 25 PM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/35910788/7d536d39-6b61-4571-a552-42efff3da5d9">

**Comment by devtooligan** [comment]
oh yes!  thank you so much, that worked :D closing
