### ISSUE TITLE
Diagram can get in corrupt state and unaccesible

### ISSUE THREAD

**Issue by devtooligan** [Mermaid-Chart/issue-tracker#46]
**Describe the bug**
Not sure why, I was attempting to add a `< br>` to a participant name and all the sudden it crashed and now when i try to open the diagram it just hangs and hangs.  I've made the diagram public so hopefully you can see it here:

https://www.mermaidchart.com/app/projects/3d0c1ec3-a4c2-4d7e-a665-f19d83e27f98/diagrams

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome

**Comment by huynhicode** [comment]
@devtooligan 

Looks like the diagram link being shared has restricted access. You can manage the settings by clicking on the Share button in the top right corner of the Editor.

<img width="301" alt="Screenshot 2023-11-19 at 5 49 33 PM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/35910788/5118fc6a-b947-4689-b069-5b89c12a8f57">

At the moment, I am not able to view the code or diagram.

Something you can try is `<br />`.  I noticed that typed  `< br>` above (without the forward slash) - not sure if this is a typo.

**Comment by devtooligan** [comment]
hmm i think i deleted by accident now.  ill close this and report again if it happens in the future
