### ISSUE TITLE
Option to expand toolbar

### ISSUE THREAD

**Issue by vrachev** [Mermaid-Chart/issue-tracker#48]
Would be great to be able to expand the toolbar to show the text values, to more easily know what tools do. I've uploaded what this feature looks like in a different app (windmill). 

https://github.com/Mermaid-Chart/issue-tracker/assets/4767834/68d48e06-d4de-4848-ac67-f361cf543dea

**Comment by huynhicode** [comment]
Thanks for the suggestion @vrachev - I agree and this is something we have on our roadmap!

**Comment by vrachev** [comment]
Yay! Thanks

**Comment by huynhicode** [comment]
@vrachev we have added labels to the icons in our Editor!

![Screenshot 2024-01-15 at 7 45 18 PM](https://github.com/Mermaid-Chart/issue-tracker/assets/35910788/36e2fe87-29a6-403e-8bc6-45f9af6a0049)

![Screenshot 2024-01-15 at 7 45 25 PM](https://github.com/Mermaid-Chart/issue-tracker/assets/35910788/e6094ca7-3d57-4a1a-97cd-bd90d7a55222)

Hope this is helpful!  Closing ticket as completed.
