### ISSUE TITLE
PNG Resolution too low

### ISSUE THREAD

**Issue by fredwojna** [Mermaid-Chart/issue-tracker#5]
**Describe the bug**
PNG resolution is too low when exporting a large entity-relationship model.

**To Reproduce**
1. Create a big Entity Relationship model with about 60 entities (including attribute description per entity)
2. Click on the PNG button to export
3. Open the PNG file
4. The image has not enough resolution to zoom in. Everything is pixelated

**Expected behavior**
I would like to have a usable PNG when I work on large entity relationship models

**Screenshots**
Check the screenshot

**Desktop (please complete the following information):**
 - OS: Macos Ventura 13.4
 - Browser: Safari
 - Version Version 16.5 (18615.2.9.11.4)
<img width="1558" alt="SCR-20230708-owrk" src="https://github.com/Mermaid-Chart/issue-tracker/assets/20560280/44b64ee8-fdcb-48e8-8cb3-abd5f6839c2d">

**Smartphone (please complete the following information):**

**Comment by knsv** [comment]
Hi!

Thanks for reporting.

The pngs exported is in 4K resolution. I need further zoom capabilities I would suggest you export the diagram as a SVG instead that is vector based. Increasing the size of the PNGs further would make them a bit too large for common diagrams.
