### ISSUE TITLE
Password reset form doesn't allow submit

### ISSUE THREAD

**Issue by caribou-code** [Mermaid-Chart/issue-tracker#51]
**Describe the bug**

I've created a new account but my password manager didn't save the password, so I've got a password reset link. The password reset page doesn't work at all and there seems to be a multitude of things wrong it:

1. The console is warning about failing to load a resource (429 error).
2. Some personal tracking data is being console logged, which has no business being there in a production app
3. When filling the form, I'm sometimes getting an error 'Sorry passwords do not match' even though they do
4. The submit button only seems to exit the disabled state on blur event from a form field (very strange behaviour)
5. Hitting the enter key or clicking the button does nothing (no network requests or UI feedback)

I've tried the above in Safari, Firefox and Chrome on OSX. It appears to be consistent on all browsers. I am unable to get into my new account at all currently - not the best start!

**Comment by jgreywolf** [comment]
@caribou-code This issue should be resolved now.  I will go and make sure that we are not logging any extra info to console as well.
