### ISSUE TITLE
Infinite refresh loop

### ISSUE THREAD

**Issue by joseehilton147** [Mermaid-Chart/issue-tracker#53]
**Describe the bug**
When I log in, it takes a long time to open my created diagrams and when it finally loads, it keeps refreshing the page infinitely, giving several request errors to the API.

endpoint https://www.mermaidchart.com/rest-api/users/me is being called 2 times when i enter the diagram page and on second request is giving Internal Server Error

this is the payload from first request:

{
    "id": "1987bc59-5b54-4356-9305-285eb4189f44",
    "authID": "", // dont know if is sensitive, if dont i update with it
    "analyticsID": "5c04e32b-d6a8-459c-b5fa-b9c96a50c812",
    "emailAddress": "joseehilton147@gmail.com",
    "fullName": "Jose",
    "theme": null,
    "mermaidTheme": "mc",
    "avatarUrl": "",
    "isB2C": true,
    "allowMarketingEmail": false,
    "allowProductEmail": true,
    "subscriptionTier": "free",
    "subscriptionInterval": "monthly",
    "subscriptionEnd": "2024-02-20T20:38:56.927Z",
    "createdAt": "2024-02-20T20:38:56.927Z",
    "updatedAt": "2024-02-21T15:12:49.342Z"
}

**To Reproduce**
1. Enter in any diagram
2. wait refresh

**Expected behavior**
Dont refresh the page

**Screenshots**
<img width="2532" alt="image" src="https://github.com/Mermaid-Chart/issue-tracker/assets/53986027/a10db619-dca4-4b03-a081-523548e899c3">

**Desktop (please complete the following information):**
 - OS: Apple M2 Pro sonoma 14.3
 - Browser: chrome and safari
 - Version: chrome: 119.0.6045.159 | safari: 17.3

**Comment by ashishjain0512** [comment]
@joseehilton147  We have addressed the infinite loop issue, can you confirm if this is fixed for you.

**Comment by joseehilton147** [comment]
fixed
