### ISSUE TITLE
Bug while trying to create a Mermaid Account

### ISSUE THREAD

**Issue by ahandsel** [Mermaid-Chart/issue-tracker#54]
**Describe the bug**
The `Confirm Your Signup` email's `Confirm your email` link is broken

**To Reproduce**
1. Go to <https://www.mermaidchart.com/app/sign-up>
2. Fill out the email and password fields and click the `Create account` button
3. Open the `Confirm Your Signup` email
4. Click on the URL-embedded `Confirm your email` text
5. Fail to open the page due to incorrect URL.

**Expected behavior**
Expected: `https://www.mermaidchart.com/app/auth/confirm?token_hash=pkce_...`

Actual: `https://www.mermaidchart.comapp/auth/confirm?token_hash=pkce_...`

Typo: There is a missing `/` between `.com` and `app`.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Additional context**
Once the missing `/` was added, the URL worked and I was able to confirm my email address.

**Comment by jgreywolf** [comment]
Apologize for the delay in response.  This was fixed as of 02/2024
