### ISSUE TITLE
Free trial cancelled, charged for yearly subscription anyway.

### ISSUE THREAD

**Issue by AldricOgouyemi** [Mermaid-Chart/issue-tracker#55]
I started a free trial for a project I had for school. Immediately after signing up, I recall canceling the subscription. However, I just saw that my bank account was billed $111 (CAD) for a yearly subscription. Why and how did this happen?

**Comment by huynhicode** [comment]
@AldricOgouyemi Thanks for bringing this to our attention. We're sorry for any inconvenience this may have caused. A member of our team will reach out to you via the email we received from you. I am closing this ticket in the meantime.
