### ISSUE TITLE
Team invitees status does not change from Pending

### ISSUE THREAD

**Issue by dominic-banister-swo** [Mermaid-Chart/issue-tracker#7]
**Describe the bug**
After inviting a new team mate to join Mermaid and they have signed up, their status in the Team Pending Invites doesnt change so I cant add them to a Team and share work

**To Reproduce**
1. Invite a new Team Member 
2. Invitee signs up for Mermaid
3. Invitee status does not change in Mermaid  so they can't be added to a Team

**Expected behavior**
Invitee signs up and the Status of team member changes so they can be added to a Team

**Screenshots**
The invitees have signed up but their status does not change

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 

**Additional context**
Does everyone in the Team need a Pro license?

**Comment by knsv** [comment]
The organiser is the only one that needs a pro-license. He/she will be charged for the licenses and the users will receive pro-licenses that way.

**Comment by tommytikea** [comment]
Any news on this ? I have the same issue

**Comment by knsv** [comment]
Thanks for bringing this to us again. We suspect this can happen for several reasons. This will, for instance happen if a user is invited to an organization with one email address but signs in with another address when accepting the invite. We are releasing better information for the user when the invitation fails as a first step.

**Comment by tommytikea** [comment]
FYI!

The user signed in with the correct mail, i tried two different emails.
/Tommy

**Comment by knsv** [comment]
I understand! We've just added more logging to track down this issue. 

Please give it another go and send the email you used for the invite, along with the approximate time the user accepted the invite, to [support@mermaidchart.com](mailto:support@mermaidchart.com)?

This information will help us zero in on the issue and get this sorted out as soon as possible.

Thanks again for working with us on this!

**Comment by tommytikea** [comment]
So let me ask something,

Every member I invite to collaborate with me, do I have to pay 100USD ?

/Tommy
