### ISSUE TITLE
Free Tier Has no option for Teams.

### ISSUE THREAD

**Issue by brettembrey** [Mermaid-Chart/issue-tracker#74]
**Describe the bug**
Hi yes, on the pricing page for free teir there is an option for teams and it has a check mark however cannot find a way to invite 1 team member, there is no link for it (at least where I can see).

**To Reproduce**
1. Go to profile on a free tier account
2. No option for teams.
3. Go to the pricing page to show all features and you will see under free tier an option for Teams.

https://www.mermaidchart.com/pricing

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/115599690/ca48a939-eaa1-4910-a652-ca87e1c029d9)

**Comment by huynhicode** [comment]
Hi @brettembrey - Ah, good catch! Sorry for the oversight; the Teams feature is coming soon to the Free tier!

We will be updating the Pricing cards and features list in the meantime.
