### ISSUE TITLE
Not able to edit diagram title

### ISSUE THREAD

**Issue by sureshHARDIYA** [Mermaid-Chart/issue-tracker#8]
**Describe the bug**
Create a diagram with default title and save it. Then try to edit it. 

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2022919/0d9be552-47ab-49e4-ac4d-bb2c3e6e434e)

It is allowed to edit title but it is not saved. If you refresh the page, then it reverts back to "Untitled Diagram".

**Comment by knsv** [comment]
Thanks for reporting @sureshHARDIYA!

I can not reproduce this issue. Perhaps you did not leave the text field, this is when the value is saved. I will assign this issue to @huynhicode who is the UX engineer as Mermaid Chart.

**Comment by huynhicode** [comment]
Thanks, @knsv!

Hi @sureshHARDIYA, we recently merged an update for the editable diagram title field.  When you enter a diagram title, navigating away from the field will save your changes.  You can also hit the `tab` or `return` key on your keyboard and your updated diagram title will save.

I hope this is helpful.  Please reach out with additional questions or comments.
