### ISSUE TITLE
Pro Subscription Payment on Monthly Basis

### ISSUE THREAD

**Issue by shubmkh** [Mermaid-Chart/issue-tracker#82]
Currently I can not discover a monthly subscription payment. I don't want to get into a yearly commitment upfront, since I am not sure my requirement is that long. How can I subscribe for Pro on Monthly Payment?

**Comment by huynhicode** [comment]
Hi @shubmkh, thanks for reaching out. We do not currently support monthly subscriptions. If you have further questions, please feel free to email us at hello@mermaidchart.com
